// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "default"
                ],
                "summary": "Database Health Indicator",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.Hello"
                        }
                    }
                }
            }
        },
        "/hello": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "default"
                ],
                "summary": "Hello World",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.Hello"
                        }
                    }
                }
            }
        },
        "/v1/categories": {
            "get": {
                "description": "Get List of ` + "`" + `Categories` + "`" + `",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "limit of results",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/routes.CategoriesResp"
                            }
                        }
                    }
                }
            }
        },
        "/v1/categories/{id}": {
            "get": {
                "description": "Get ` + "`" + `Category` + "`" + ` Info By ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/product.Category"
                        }
                    }
                }
            }
        },
        "/v1/categories/{id}/children": {
            "get": {
                "description": "Get List of ` + "`" + `Categories` + "`" + ` as Children of a ` + "`" + `Category` + "`" + ` with ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/product.Category"
                        }
                    }
                }
            }
        },
        "/v1/countries": {
            "get": {
                "description": "Get List of ` + "`" + `Country` + "`" + `es by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "utility"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/address.Country"
                            }
                        }
                    }
                }
            }
        },
        "/v1/home-page": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "homepage"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.HomePageResp"
                        }
                    }
                }
            }
        },
        "/v1/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "parameters": [
                    {
                        "description": "Login Data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserLoginDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.User"
                        }
                    }
                }
            }
        },
        "/v1/logout": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Log out of the current session",
                "responses": {}
            }
        },
        "/v1/products": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Category ID",
                        "name": "category_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "limit of results",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/routes.ProductsResp"
                        }
                    }
                }
            }
        },
        "/v1/products/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/product.Product"
                        }
                    }
                }
            }
        },
        "/v1/profile": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Get Profile Info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.User"
                        }
                    }
                }
            },
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Update Profile",
                "parameters": [
                    {
                        "description": "Profile Update Dto",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.ProfileUpdateDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/user.User"
                        }
                    }
                }
            }
        },
        "/v1/profile/addresses": {
            "get": {
                "description": "Get List of ` + "`" + `Address` + "`" + `es for the current ` + "`" + `User` + "`" + `",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "limit of results",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/routes.AddressesResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new ` + "`" + `Address` + "`" + ` for the current ` + "`" + `User` + "`" + `",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "parameters": [
                    {
                        "description": "Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/address.AddressCreateDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/address.Address"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/profile/addresses/{id}": {
            "get": {
                "description": "Get ` + "`" + `Address` + "`" + ` Info By ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Address ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/address.Address"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an ` + "`" + `Address` + "`" + ` by it's ` + "`" + `ID` + "`" + `.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Address ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/address.AddressUpdateDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/address.Address"
                        }
                    }
                }
            },
            "delete": {
                "description": "Get ` + "`" + `Address` + "`" + ` Info By ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Address ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/address.Address"
                        }
                    }
                }
            }
        },
        "/v1/signup": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "parameters": [
                    {
                        "description": "Sign Up Data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserSignUpDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/user.User"
                        }
                    }
                }
            }
        },
        "/v1/states": {
            "get": {
                "description": "Get List of ` + "`" + `States` + "`" + `es by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "utility"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/address.State"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "address.Address": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string",
                    "example": "Tokyo"
                },
                "company": {
                    "type": "string"
                },
                "country": {
                    "$ref": "#/definitions/address.Country"
                },
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "ext": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string",
                    "example": "John"
                },
                "id": {
                    "type": "integer"
                },
                "lastName": {
                    "type": "string",
                    "example": "Doe"
                },
                "phone": {
                    "type": "string",
                    "example": "+11349503120"
                },
                "state": {
                    "$ref": "#/definitions/address.State"
                },
                "streetAddress1": {
                    "type": "string"
                },
                "streetAddress2": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "verified": {
                    "type": "boolean"
                },
                "zip": {
                    "type": "string"
                }
            }
        },
        "address.AddressCreateDto": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string",
                    "example": "Los Angeles"
                },
                "company": {
                    "type": "string"
                },
                "countryID": {
                    "type": "integer",
                    "minimum": 1
                },
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "ext": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string",
                    "example": "John"
                },
                "lastName": {
                    "type": "string",
                    "example": "Doe"
                },
                "phone": {
                    "type": "string",
                    "example": "+12380941034"
                },
                "stateID": {
                    "type": "integer",
                    "minimum": 1
                },
                "streetAddress1": {
                    "type": "string"
                },
                "streetAddress2": {
                    "type": "string"
                },
                "zip": {
                    "type": "string"
                }
            }
        },
        "address.AddressUpdateDto": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string",
                    "example": "New York"
                },
                "company": {
                    "type": "string"
                },
                "countryId": {
                    "type": "integer",
                    "minimum": 1
                },
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "ext": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string",
                    "example": "Jane"
                },
                "lastName": {
                    "type": "string",
                    "example": "Doe"
                },
                "phone": {
                    "type": "string",
                    "example": "+12380941034"
                },
                "stateId": {
                    "type": "integer",
                    "minimum": 1
                },
                "streetAddress1": {
                    "type": "string"
                },
                "streetAddress2": {
                    "type": "string"
                },
                "zip": {
                    "type": "string"
                }
            }
        },
        "address.Country": {
            "type": "object",
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "position": {
                    "type": "integer"
                },
                "ppCode": {
                    "type": "string"
                }
            }
        },
        "address.State": {
            "type": "object",
            "properties": {
                "fullName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "info": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tax": {
                    "type": "number"
                }
            }
        },
        "model.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "'field' has failed the constraint: 'constraint' (vale: 'actual value')"
                },
                "status": {
                    "type": "integer",
                    "example": 400
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "product.Category": {
            "type": "object",
            "properties": {
                "brandAttributeCollapsed": {
                    "type": "boolean"
                },
                "brandAttributeEnabled": {
                    "type": "boolean"
                },
                "buttonContent": {
                    "type": "string"
                },
                "buttonEnable": {
                    "type": "boolean"
                },
                "buttonTitle": {
                    "type": "string"
                },
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/product.Category"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "customCategory": {
                    "type": "boolean"
                },
                "defaultSorting": {
                    "type": "boolean"
                },
                "displayTitle": {
                    "type": "string"
                },
                "firstDescription": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "metaDescription": {
                    "type": "string"
                },
                "metaTitle": {
                    "type": "string"
                },
                "position": {
                    "type": "integer"
                },
                "priceAttributeCollapsed": {
                    "type": "boolean"
                },
                "priceAttributeEnabled": {
                    "type": "boolean"
                },
                "published": {
                    "type": "boolean"
                },
                "secondDescription": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "product.Manufacturer": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "product.Product": {
            "type": "object",
            "properties": {
                "application": {
                    "type": "string"
                },
                "caPropWarning": {
                    "type": "boolean"
                },
                "createdAt": {
                    "type": "string"
                },
                "crossRef": {
                    "type": "string"
                },
                "customLabel": {
                    "type": "string"
                },
                "declareValue": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "discontinued": {
                    "type": "boolean"
                },
                "discontinuedReplacement": {
                    "type": "string"
                },
                "discountDeadline": {
                    "type": "string"
                },
                "discountPrice": {
                    "type": "number"
                },
                "discountStartDate": {
                    "type": "string"
                },
                "documentation": {
                    "type": "string"
                },
                "faqGroupLabel": {
                    "type": "string"
                },
                "features": {
                    "type": "string"
                },
                "fluid": {
                    "type": "boolean"
                },
                "freeShipping": {
                    "type": "boolean"
                },
                "freightOnly": {
                    "type": "boolean"
                },
                "height": {
                    "type": "number"
                },
                "hideManufacturer": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/product.ProductImage"
                    }
                },
                "inStockAtSupplier": {
                    "type": "boolean"
                },
                "length": {
                    "type": "number"
                },
                "listPostion": {
                    "type": "integer"
                },
                "lwhUnit": {
                    "type": "string"
                },
                "madeInUsa": {
                    "type": "boolean"
                },
                "manufacturer": {
                    "description": "Joins",
                    "allOf": [
                        {
                            "$ref": "#/definitions/product.Manufacturer"
                        }
                    ]
                },
                "metaDescription": {
                    "type": "string"
                },
                "metaTitle": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "nonPickup": {
                    "type": "boolean"
                },
                "notLeadFree": {
                    "type": "boolean"
                },
                "note": {
                    "type": "string"
                },
                "partNumber": {
                    "type": "string"
                },
                "pickupDiscount": {
                    "type": "number"
                },
                "pickupOnly": {
                    "type": "boolean"
                },
                "pickupPrice": {
                    "type": "number"
                },
                "possibleFraud": {
                    "type": "boolean"
                },
                "pricePerFoot": {
                    "type": "number"
                },
                "priceRangeId": {
                    "type": "integer"
                },
                "published": {
                    "type": "boolean"
                },
                "replacement": {
                    "type": "string"
                },
                "reviewGroupLabel": {
                    "type": "string"
                },
                "sellPrice": {
                    "type": "number"
                },
                "sellQty": {
                    "type": "integer"
                },
                "shelfIdExtra": {
                    "type": "string"
                },
                "shipDedicatedBox": {
                    "type": "integer"
                },
                "shipSelfPackaging": {
                    "type": "boolean"
                },
                "shipSeparately": {
                    "type": "boolean"
                },
                "showMapPrice": {
                    "type": "boolean"
                },
                "slug": {
                    "type": "string"
                },
                "specOrder": {
                    "type": "boolean"
                },
                "stockQuantity": {
                    "type": "integer"
                },
                "techSpecs": {
                    "type": "string"
                },
                "temporaryUnavailable": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                },
                "upc": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "usuallyShips": {
                    "type": "string"
                },
                "warranty": {
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                },
                "weightUnits": {
                    "type": "string"
                },
                "width": {
                    "type": "number"
                }
            }
        },
        "product.ProductImage": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "delete": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "position": {
                    "type": "integer"
                },
                "src": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "routes.AddressesResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "currentPage": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/address.Address"
                    }
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "routes.CategoriesResp": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "currentPage": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/product.Category"
                    }
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "routes.Hello": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "routes.HomePageResp": {
            "type": "object",
            "properties": {
                "brands": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/product.Manufacturer"
                    }
                },
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/product.Category"
                    }
                }
            }
        },
        "routes.ProductsResp": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "currentPage": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/product.Product"
                    }
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "routes.ProfileUpdateDto": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "John Doe"
                }
            }
        },
        "user.User": {
            "type": "object",
            "properties": {
                "addresses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/address.Address"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "user.UserLoginDto": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "Very Strong Password"
                }
            }
        },
        "user.UserSignUpDto": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "avEryStrongPass@93"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Pex Universe API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
