basePath: /
definitions:
  model.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
  model.UserLoginDto:
    properties:
      email:
        example: john@example.com
        type: string
      password:
        example: Very Strong Password
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  model.UserSignUpDto:
    properties:
      email:
        example: john@example.com
        type: string
      name:
        example: John Doe
        type: string
      password:
        example: avEryStrongPass@93
        minLength: 8
        type: string
    required:
    - email
    - name
    - password
    type: object
  server.Hello:
    properties:
      message:
        type: string
    type: object
  server.ProfileUpdateDto:
    properties:
      name:
        example: John Doe
        type: string
    required:
    - name
    type: object
host: localhost:8080
info:
  contact: {}
  title: Pex Universe API
  version: "1.0"
paths:
  /health:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.Hello'
      summary: Database Health Indicator
      tags:
      - default
  /hello:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.Hello'
      summary: Hello World
      tags:
      - default
  /v1/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.UserLoginDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      tags:
      - auth
  /v1/logout:
    post:
      responses: {}
      summary: Log out of the current session
      tags:
      - auth
  /v1/profile:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: Get Profile Info
      tags:
      - profile
    put:
      parameters:
      - description: Profile Update Dto
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/server.ProfileUpdateDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.User'
      summary: Update Profile
      tags:
      - profile
  /v1/signup:
    post:
      consumes:
      - application/json
      parameters:
      - description: Sign Up Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.UserSignUpDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.User'
      tags:
      - auth
swagger: "2.0"
